import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import NavBar from "./_nav-bar/NavBar";
import "./globals.css";

import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import AuthProvider from "./_auth/Provider";
import Footer from "./_nav-bar/Footer";
import QueryClientProvider from "./QueryClientProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <>
          <QueryClientProvider>
            <AuthProvider>
              <Theme accentColor="amber" grayColor="sage">
                <NavBar />
                <main className="min-h-screen sm:min-h-[50vh] md:min-h-[75vh] lg:min-h-[100vh]">
                  <Container>{children}</Container>
                </main>
                <Footer />
                {/* <ThemePanel /> */}
              </Theme>
            </AuthProvider>
          </QueryClientProvider>
          <Toaster />
        </>
      </body>
    </html>
  );
}
