import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./_nav-bar/NavBar";

import { Inter } from "next/font/google";
import AuthProvider from "./_auth/Provider";
import QueryClientProvider from "./QueryClientProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <>
          <QueryClientProvider>
            <AuthProvider>
              <Theme accentColor="amber" grayColor="sage">
                <NavBar />
                <main>
                  <Container>{children}</Container>
                </main>
                {/* <ThemePanel /> */}
              </Theme>
            </AuthProvider>
          </QueryClientProvider>
          <Toaster />
        </>
      </body>
    </html>
  );
}
